language: node_js
node_js:
  - "lts/*"
sudo: enabled
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
    - CC_TEST_REPORTER_ID=147f28703d3ae0d7c498d8dbedbcb1adb912ffb4873e0b0c644fb78346404a93
    - PGPORT=5433
cache:
  directories:
    - "node_modules"
install:
  - npm install
before_script:
  - sudo -u postgres psql -c 'create database BookAMeal_test;'
  - sudo -u postgres psql -c "CREATE USER root WITH PASSWORD 'password';"
  - sequelize db:migrate:all
  - chmod 0755 ./node_modules/.bin/mocha
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm test
after_success:
  - npm run coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT