swagger: '2.0'
info:
  description: |
    Book-A-Meal is an application that allows customers to make food orders and helps the food
    vendor know what the customers want to eat
  version: "1"
  title: Book A Meal API
# host: https://book-a-meal-andela-31.herokuapp.com
paths:
  /api/v1/auth/signup:
    post:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Create a new user
          required: true
          schema:
            $ref: '#/definitions/SignUp'
          x-examples:
            application/json: "
              {\r\n\"firstName\":\"Tovieye\",
              \r\n\"lastName\":\"Ozi\",
              \r\n\"email\":\"ozimos83@yahoo.com\",
              \r\n\"password\":\"test\"\r\n,
              \r\n\"confirmPassword\":\"test\"\r\n}"
      responses:
        201:
          description: Return user details as saved on database and success message
          schema:
            $ref: '#/definitions/SignUp'
        405:
          description: Invalid input
  /api/v1/auth/login:
    post:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Log a user in
          required: true
          schema:
            $ref: '#/definitions/Login'
          x-examples:
            application/json: "{\r\n\"email\":\"ozimos83@yahoo.com\",\r\n\"password\":\"test\"\r\n}"
      responses:
        200:
          description: Return user details as saved on database and success message
          schema:
            $ref: '#/definitions/SignUp'
        405:
          description: Invalid input
  /api/v1/meals:
    post:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Add a new meal
          required: true
          schema:
            $ref: '#/definitions/Meals'
          x-examples:
            application/json: "{\r\n\"title\":\"amala and ewedu\",\r\n\"description\":\"satisfying\",\r\n\"price\":\"2000\",\r\n\"imageUrl\":\"https://cdn.pixabay.com/photo/2017/11/23/13/50/pumpkin-soup-2972858_960_720.jpg\",\r\n\"userId\":\"67217a96-9fa9-451b-8244-738f9ba8f63b\"\r\n}"
      responses:
        201:
          description: Return meal details as saved on database
          schema:
            $ref: '#/definitions/Meals'
        405:
          description: Invalid input
      security:
        - bookameal_auth:
          - write:records
          - read:records
    get:
      responses:
        200:
          description: Return all meals details as saved on database
        405:
          description: Invalid input
      security:
        - bookameal_auth:
          - write:records
          - read:records
  /api/v1/meals/{mealId}:
    put:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: false
          schema:
            $ref: '#/definitions/Meals'
          x-examples:
            application/json: "{\r\n\"title\":\"chicken wings with chips\",\r\n\"description\":\"exotic\"\r\n}"
        - name: mealId
          in: path
          description: Meal Id
          required: true
          type: string
      responses:
        200:
          description: Return meal details as updated on database
        405:
          description: Invalid input
      security:
        - bookameal_auth:
          - write:records
          - read:records
    delete:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: mealId
          in: path
          description: Meal Id
          required: true
          type: string
      responses:
        200:
          description: Return meal details as saved on database
        405:
          description: Invalid input
      security:
        - bookameal_auth:
          - write:records
          - read:records
  /api/v1/orders/{orderId}:
    put:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: false
          schema:
            $ref: '#/definitions/Orders'
          x-examples:
            application/json: "{\r\n\"meals\":[\"084a7e7c-ef72-45cd-8998-727e56af2759\", \"efe1ed43-6169-4b9c-bd2d-fcdea22f2be4\"]\r\n}"
        - name: orderId
          in: path
          description: Meal Id
          required: true
          type: string
      responses:
        200:
          description: Return order details as saved on database
        405:
          description: Invalid input
      security:
        - bookameal_auth:
          - write:records
          - read:records
  /api/v1/orders:
    post:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Orders'
          x-examples:
            application/json: "{\r\n\"description\":\"Wednesday's Menu\",\r\n\"meals\":[\"084a7e7c-ef72-45cd-8998-727e56af2759\", \"efe1ed43-6169-4b9c-bd2d-fcdea22f2be4\", \"74011cce-299a-4a9d-84b2-55398748d360\"]\r\n}"
      responses:
        200:
          description: Return order details as saved on database
        405:
          description: Invalid input
      security:
        - bookameal_auth:
          - write:records
          - read:records
    get:
      responses:
        200:
          description: Return all order details as saved on database
        405:
          description: Invalid input
      security:
        - bookameal_auth:
          - write:records
          - read:records
securityDefinitions:
  bookameal_auth:
    type: oauth2
    authorizationUrl: https://book-a-meal-andela-31.herokuapp.com/api/v1/login
    flow: implicit
    scopes:
      write:records: modify records in your account
      read:records: read your records
  api_key:
    type: apiKey
    name: api_key
    in: header
definitions:
  Meals:
    type: object
    properties:
      title:
        type: string
      description:
        type: string
      price:
        type: string
      imageUrl:
        type: string
      userId:
        type: string
        format: uuidv4
  Orders:
    type: object
    properties:
      meals:
        type: array
        items:
          type: string
          format: uuidv4
  SignUp:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
        format: email
      password:
        type: string
      confirmPassword:
        type: string
      isCaterer:
        type: boolean
  Login:
    type: object
    properties:
      email:
        type: string
        format: email
      password:
        type: string